### ISSUE TITLE
Project Explorer call migrate source - but fix includes failes if the include file was renamed

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/sourceorbit#10]
This example is using p9adt01.rch.stglabs.ibm.com machine with PAY_ORG library
There is a LIAMA user profile on this machine

<img width="472" alt="image" src="https://github.com/IBM/sourceorbit/assets/11184579/30519e5e-53ba-4b9f-bfd1-1c9ab7af2bf9">

![image](https://github.com/IBM/sourceorbit/assets/11184579/20e2c12e-9c58-480b-b723-23cc2bcfddf2)

Using the latest 1.1.0 version of the vsix, the rename of the include file to RPGLEINC succeeds, but according the log, the second run to fix includes fails because it is looking for the old name.

```
Debugger listening on ws://127.0.0.1:8720/8234ea10-de97-40d6-bf2c-8bff7dff5f60
For help, see: https://nodejs.org/en/docs/inspector
Connected and got workspace folders
{
  "uri": "file:///Users/reinhard/Documents/git/demo/payroll-from-qsys",
  "name": "payroll-from-qsys"
}
Reloading logs
Starting rename process. Do not end process.
'/Users/reinhard/Documents/git/demo/payroll-from-qsys/QPROTOSRC/ERRORTABLE.RPGLE' -> 'ERRORTABLE.pgm.RPGLE'
'/Users/reinhard/Documents/git/demo/payroll-from-qsys/QPROTOSRC/ERRORTABLE.pgm.RPGLE' -> 'ERRORTABLE.rpgleinc'
'/Users/reinhard/Documents/git/demo/payroll-from-qsys/QRPGLESRC/PAYROLL.RPGLE' -> 'PAYROLL.pgm.RPGLE'
Starting include fix process. Do not end process.
Error: ENOENT: no such file or directory, open 'QPROTOSRC/ERRORTABLE.RPGLE'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9212)
    at replaceIncludes (/Users/reinhard/.vscode/extensions/ibm.vscode-sourceorbit-1.1.0/out/server.js:24400:63)
    at /Users/reinhard/.vscode/extensions/ibm.vscode-sourceorbit-1.1.0/out/server.js:24382:9
    at Generator.next (<anonymous>)
    at fulfilled (/Users/reinhard/.vscode/extensions/ibm.vscode-sourceorbit-1.1.0/out/server.js:24322:24) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'QPROTOSRC/ERRORTABLE.RPGLE'
}
Reloading logs
Reloading logs
```
![image](https://github.com/IBM/sourceorbit/assets/11184579/1e961e25-7369-4096-8419-19cbde9414fd)

**Comment by edmundreinhardt** [comment]
Even after applying your latest vsix, I see the same behaviour above.
@worksofliam
