### ISSUE TITLE
did not handle SQLTRG (SQL Trigger) pseudo source from arcad-example

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/sourceorbit#3]
Attempted to run 
`so -bf bob`
after cloning `git@github.com:aecspades/arcad-example.git`
got the following failure.  
```
QSQLSRC/ORD701.SQLTRG - Failed to parse file.
QSQLSRC/ORD701.SQLTRG
TypeError: Cannot read properties of undefined (reading 'range')
    at Document.getStatementGroups (/Users/reinhard/Documents/git/sourceorbit/cli/dist/index.js:6201:57)
    at Targets.createSqlTargets (/Users/reinhard/Documents/git/sourceorbit/cli/dist/index.js:4217:33)
    at Targets.handlePath (/Users/reinhard/Documents/git/sourceorbit/cli/dist/index.js:3933:26)
    at async main (/Users/reinhard/Documents/git/sourceorbit/cli/dist/index.js:142:24)
[ERROR] Report this issue to us with an example: github.com/halcyon-tech/vscode-rpgle/issues
```

**Comment by edmundreinhardt** [comment]
contents of file are
```
      /*%METADATA                                                     */
      /* %TEXT                                                        */
      /*%EMETADATA                                                    */

Create Trigger ORD701_Insert_order
After Insert  on order
Referencing  New As N

For Each Row
Program Name ORD701
set option sqlPath = *LIBL
Begin

  Update Customer set culastord = n.ordate
         where cuid = N.orcuid;
End
```

**Comment by worksofliam** [comment]
@edmundreinhardt New commit is in which will solve this bug.

**Comment by worksofliam** [comment]
Now it is parsing. Thanks!

```

QSQLSRC/ORD701.SQLTRG - ORD701_Insert_order (PGM) name is longer than 10 characters. Assuming system name (object name) is 'ORD701'
ORD701.PGM: QSQLSRC/ORD701.SQLTRG
```

**Comment by edmundreinhardt** [comment]
Thanks!
